# Tester les requetes et dataframe utilisés dans le Dashboard

In [2]:
import streamlit as st
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('../data/application_train_features.csv')
data = data.iloc[:, 3:]  # Je supprime des colonnes de réplication des index (je ne sais pas d'où elles viennent mais pas grave)
data.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307510 entries, 0 to 307509
Data columns (total 150 columns):
 #    Column                               Non-Null Count   Dtype
---   ------                               --------------   -----
 0    SK_ID_CURR                           307510 non-null  int64
 1    TARGET                               307510 non-null  float64
 2    FLAG_OWN_CAR                         307510 non-null  object
 3    FLAG_OWN_REALTY                      307510 non-null  int64
 4    CNT_CHILDREN                         307510 non-null  int64
 5    AMT_INCOME_TOTAL                     307510 non-null  float64
 6    AMT_CREDIT                           307510 non-null  float64
 7    AMT_ANNUITY                          307498 non-null  float64
 8    AMT_GOODS_PRICE                      307510 non-null  float64
 9    NAME_TYPE_SUITE                      306218 non-null  object
 10   NAME_INCOME_TYPE                     307510 non-null  object
 11   NAME_EDUCATION_TYPE                  307510 non-null  object
 12   NAME_FAMILY_STATUS                   307510 non-null  object
 13   NAME_HOUSING_TYPE                    307510 non-null  object
 14   REGION_POPULATION_RELATIVE           307510 non-null  float64
 15   DAYS_BIRTH                           307510 non-null  int64
 16   DAYS_EMPLOYED                        307510 non-null  float64
 17   DAYS_REGISTRATION                    307510 non-null  float64
 18   DAYS_ID_PUBLISH                      307510 non-null  int64
 19   OWN_CAR_AGE                          104582 non-null  float64
 20   FLAG_MOBIL                           307510 non-null  int64
 21   FLAG_EMP_PHONE                       307510 non-null  int64
 22   FLAG_WORK_PHONE                      307510 non-null  int64
 23   FLAG_CONT_MOBILE                     307510 non-null  int64
 24   FLAG_PHONE                           307510 non-null  int64
 25   FLAG_EMAIL                           307510 non-null  int64
 26   OCCUPATION_TYPE                      211119 non-null  object
 27   CNT_FAM_MEMBERS                      307510 non-null  float64
 28   REGION_RATING_CLIENT                 307510 non-null  int64
 29   REGION_RATING_CLIENT_W_CITY          307510 non-null  int64
 30   WEEKDAY_APPR_PROCESS_START           307510 non-null  object
 31   HOUR_APPR_PROCESS_START              307510 non-null  int64
 32   REG_REGION_NOT_LIVE_REGION           307510 non-null  int64
 33   REG_REGION_NOT_WORK_REGION           307510 non-null  int64
 34   LIVE_REGION_NOT_WORK_REGION          307510 non-null  int64
 35   REG_CITY_NOT_LIVE_CITY               307510 non-null  int64
 36   REG_CITY_NOT_WORK_CITY               307510 non-null  int64
 37   LIVE_CITY_NOT_WORK_CITY              307510 non-null  int64
 38   ORGANIZATION_TYPE                    307510 non-null  object
 39   EXT_SOURCE_1                         307510 non-null  float64
 40   EXT_SOURCE_2                         307510 non-null  float64
 41   EXT_SOURCE_3                         307510 non-null  float64
 42   APARTMENTS_AVG                       151449 non-null  float64
 43   BASEMENTAREA_AVG                     127567 non-null  float64
 44   YEARS_BEGINEXPLUATATION_AVG          157503 non-null  float64
 45   YEARS_BUILD_AVG                      103023 non-null  float64
 46   COMMONAREA_AVG                       92646 non-null   float64
 47   ELEVATORS_AVG                        143619 non-null  float64
 48   ENTRANCES_AVG                        152682 non-null  float64
 49   FLOORSMAX_AVG                        154490 non-null  float64
 50   FLOORSMIN_AVG                        98869 non-null   float64
 51   LANDAREA_AVG                         124920 non-null  float64
 52   LIVINGAPARTMENTS_AVG                 97312 non-null   float64
 53   LIVINGAREA_AVG                       153160 non-null  float64
 54   NONLIVINGAPARTMENTS_AVG              93997 non-null   float64
 55   NONLIVINGAREA_AVG                    137829 non-null  float64
 56   APARTMENTS_MODE                      151449 non-null  float64
 57   BASEMENTAREA_MODE                    127567 non-null  float64
 58   YEARS_BEGINEXPLUATATION_MODE         157503 non-null  float64
 59   YEARS_BUILD_MODE                     103023 non-null  float64
 60   COMMONAREA_MODE                      92646 non-null   float64
 61   ELEVATORS_MODE                       143619 non-null  float64
 62   ENTRANCES_MODE                       152682 non-null  float64
 63   FLOORSMAX_MODE                       154490 non-null  float64
 64   FLOORSMIN_MODE                       98869 non-null   float64
 65   LANDAREA_MODE                        124920 non-null  float64
 66   LIVINGAPARTMENTS_MODE                97312 non-null   float64
 67   LIVINGAREA_MODE                      153160 non-null  float64
 68   NONLIVINGAPARTMENTS_MODE             93997 non-null   float64
 69   NONLIVINGAREA_MODE                   137829 non-null  float64
 70   APARTMENTS_MEDI                      151449 non-null  float64
 71   BASEMENTAREA_MEDI                    127567 non-null  float64
 72   YEARS_BEGINEXPLUATATION_MEDI         157503 non-null  float64
 73   YEARS_BUILD_MEDI                     103023 non-null  float64
 74   COMMONAREA_MEDI                      92646 non-null   float64
 75   ELEVATORS_MEDI                       143619 non-null  float64
 76   ENTRANCES_MEDI                       152682 non-null  float64
 77   FLOORSMAX_MEDI                       154490 non-null  float64
 78   FLOORSMIN_MEDI                       98869 non-null   float64
 79   LANDAREA_MEDI                        124920 non-null  float64
 80   LIVINGAPARTMENTS_MEDI                97312 non-null   float64
 81   LIVINGAREA_MEDI                      153160 non-null  float64
 82   NONLIVINGAPARTMENTS_MEDI             93997 non-null   float64
 83   NONLIVINGAREA_MEDI                   137829 non-null  float64
 84   FONDKAPREMONT_MODE                   97216 non-null   object
 85   HOUSETYPE_MODE                       153213 non-null  object
 86   TOTALAREA_MODE                       159079 non-null  float64
 87   WALLSMATERIAL_MODE                   151169 non-null  object
 88   EMERGENCYSTATE_MODE                  161755 non-null  object
 89   OBS_30_CNT_SOCIAL_CIRCLE             306489 non-null  float64
 90   DEF_30_CNT_SOCIAL_CIRCLE             306489 non-null  float64
 91   OBS_60_CNT_SOCIAL_CIRCLE             306489 non-null  float64
 92   DEF_60_CNT_SOCIAL_CIRCLE             306489 non-null  float64
 93   DAYS_LAST_PHONE_CHANGE               307509 non-null  float64
 94   FLAG_DOCUMENT_2                      307510 non-null  int64
 95   FLAG_DOCUMENT_3                      307510 non-null  int64
 96   FLAG_DOCUMENT_4                      307510 non-null  int64
 97   FLAG_DOCUMENT_5                      307510 non-null  int64
 98   FLAG_DOCUMENT_6                      307510 non-null  int64
 99   FLAG_DOCUMENT_7                      307510 non-null  int64
 100  FLAG_DOCUMENT_8                      307510 non-null  int64
 101  FLAG_DOCUMENT_9                      307510 non-null  int64
 102  FLAG_DOCUMENT_10                     307510 non-null  int64
 103  FLAG_DOCUMENT_11                     307510 non-null  int64
 104  FLAG_DOCUMENT_12                     307510 non-null  int64
 105  FLAG_DOCUMENT_13                     307510 non-null  int64
 106  FLAG_DOCUMENT_14                     307510 non-null  int64
 107  FLAG_DOCUMENT_15                     307510 non-null  int64
 108  FLAG_DOCUMENT_16                     307510 non-null  int64
 109  FLAG_DOCUMENT_17                     307510 non-null  int64
 110  FLAG_DOCUMENT_18                     307510 non-null  int64
 111  FLAG_DOCUMENT_19                     307510 non-null  int64
 112  FLAG_DOCUMENT_20                     307510 non-null  int64
 113  FLAG_DOCUMENT_21                     307510 non-null  int64
 114  AMT_REQ_CREDIT_BUREAU_HOUR           265991 non-null  float64
 115  AMT_REQ_CREDIT_BUREAU_DAY            265991 non-null  float64
 116  AMT_REQ_CREDIT_BUREAU_WEEK           265991 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_MON            265991 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_QRT            265991 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_YEAR           265991 non-null  float64
 120  NAME_CONTRACT_TYPE_CASH_LOAN         307510 non-null  int64
 121  NAME_CONTRACT_TYPE_REVOLVING_LOAN    307510 non-null  int64
 122  CNT_DOC_TOTAL                        307510 non-null  int64
 123  RATIO_INCOME_TO_FAM_MEMBERS          307510 non-null  float64
 124  RATIO_AMT_CREDIT_TO_AMT_GOODS_PRICE  307510 non-null  float64
 125  FLAG_STABLE_INCOME_TYPE              307510 non-null  int64
 126  FLAG_RISKED_ORGANIZATION_TYPE        307510 non-null  int64
 127  NEW_AMT_REQ_CREDIT_BUREAU_WEEK       265991 non-null  float64
 128  CNT_PREV                             307510 non-null  float64
 129  AMT_PREV_SUM                         307510 non-null  float64
 130  AMT_PREV_SUM_DEBT                    307510 non-null  float64
 131  AMT_PREV_SUM_OVERDUE                 307510 non-null  float64
 132  AMT_PREV_MAX_OVERDUE                 307510 non-null  float64
 133  CNT_CREDIT                           307510 non-null  float64
 134  AMT_CREDIT_SUM                       307510 non-null  float64
 135  AMT_CREDIT_SUM_DEBT                  307510 non-null  float64
 136  AMT_CREDIT_SUM_OVERDUE               307510 non-null  float64
 137  AMT_CREDIT_MAX_OVERDUE               307510 non-null  float64
 138  CNT_ALL                              307510 non-null  float64
 139  AMT_ALL_SUM                          307510 non-null  float64
 140  AMT_ALL_SUM_DEBT                     307510 non-null  float64
 141  AMT_ALL_SUM_OVERDUE                  307510 non-null  float64
 142  AMT_ALL_MAX_OVERDUE                  307510 non-null  float64
 143  CODE_GENDER_F                        307510 non-null  int64
 144  CODE_GENDER_M                        307510 non-null  int64
 145  CODE_GENDER_XNA                      307510 non-null  int64
 146  AMT_ALL_SUM_MEAN                     307510 non-null  float64
 147  RATIO_ALL_SUM_OVERDUE_TO_INCOME      307510 non-null  float64
 148  RATIO_ALL_MAX_OVERDUE_TO_INCOME      307510 non-null  float64
 149  RATIO_ALL_SUM_DEBT_TO_INCOME         307510 non-null  float64
dtypes: float64(89), int64(48), object(13)
memory usage: 351.9+ MB

In [10]:
client_base =  pd.read_csv('../data/application_test_features.csv')
client_base = client_base.iloc[:, 3:]  # Je supprime des colonnes de réplication des index (je ne sais pas d'où elles viennent mais pas grave)
client_base.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Data columns (total 150 columns):
 #    Column                               Non-Null Count  Dtype
---   ------                               --------------  -----
 0    SK_ID_CURR                           48744 non-null  int64
 1    TARGET                               0 non-null      float64
 2    FLAG_OWN_CAR                         48744 non-null  object
 3    FLAG_OWN_REALTY                      48744 non-null  int64
 4    CNT_CHILDREN                         48744 non-null  int64
 5    AMT_INCOME_TOTAL                     48744 non-null  float64
 6    AMT_CREDIT                           48744 non-null  float64
 7    AMT_ANNUITY                          48720 non-null  float64
 8    AMT_GOODS_PRICE                      48744 non-null  float64
 9    NAME_TYPE_SUITE                      47833 non-null  object
 10   NAME_INCOME_TYPE                     48744 non-null  object
 11   NAME_EDUCATION_TYPE                  48744 non-null  object
 12   NAME_FAMILY_STATUS                   48744 non-null  object
 13   NAME_HOUSING_TYPE                    48744 non-null  object
 14   REGION_POPULATION_RELATIVE           48744 non-null  float64
 15   DAYS_BIRTH                           48744 non-null  int64
 16   DAYS_EMPLOYED                        48744 non-null  float64
 17   DAYS_REGISTRATION                    48744 non-null  float64
 18   DAYS_ID_PUBLISH                      48744 non-null  int64
 19   OWN_CAR_AGE                          16432 non-null  float64
 20   FLAG_MOBIL                           48744 non-null  int64
 21   FLAG_EMP_PHONE                       48744 non-null  int64
 22   FLAG_WORK_PHONE                      48744 non-null  int64
 23   FLAG_CONT_MOBILE                     48744 non-null  int64
 24   FLAG_PHONE                           48744 non-null  int64
 25   FLAG_EMAIL                           48744 non-null  int64
 26   OCCUPATION_TYPE                      33139 non-null  object
 27   CNT_FAM_MEMBERS                      48744 non-null  float64
 28   REGION_RATING_CLIENT                 48744 non-null  int64
 29   REGION_RATING_CLIENT_W_CITY          48744 non-null  int64
 30   WEEKDAY_APPR_PROCESS_START           48744 non-null  object
 31   HOUR_APPR_PROCESS_START              48744 non-null  int64
 32   REG_REGION_NOT_LIVE_REGION           48744 non-null  int64
 33   REG_REGION_NOT_WORK_REGION           48744 non-null  int64
 34   LIVE_REGION_NOT_WORK_REGION          48744 non-null  int64
 35   REG_CITY_NOT_LIVE_CITY               48744 non-null  int64
 36   REG_CITY_NOT_WORK_CITY               48744 non-null  int64
 37   LIVE_CITY_NOT_WORK_CITY              48744 non-null  int64
 38   ORGANIZATION_TYPE                    48744 non-null  object
 39   EXT_SOURCE_1                         48744 non-null  float64
 40   EXT_SOURCE_2                         48744 non-null  float64
 41   EXT_SOURCE_3                         48744 non-null  float64
 42   APARTMENTS_AVG                       24857 non-null  float64
 43   BASEMENTAREA_AVG                     21103 non-null  float64
 44   YEARS_BEGINEXPLUATATION_AVG          25888 non-null  float64
 45   YEARS_BUILD_AVG                      16926 non-null  float64
 46   COMMONAREA_AVG                       15249 non-null  float64
 47   ELEVATORS_AVG                        23555 non-null  float64
 48   ENTRANCES_AVG                        25165 non-null  float64
 49   FLOORSMAX_AVG                        25423 non-null  float64
 50   FLOORSMIN_AVG                        16278 non-null  float64
 51   LANDAREA_AVG                         20490 non-null  float64
 52   LIVINGAPARTMENTS_AVG                 15964 non-null  float64
 53   LIVINGAREA_AVG                       25192 non-null  float64
 54   NONLIVINGAPARTMENTS_AVG              15397 non-null  float64
 55   NONLIVINGAREA_AVG                    22660 non-null  float64
 56   APARTMENTS_MODE                      24857 non-null  float64
 57   BASEMENTAREA_MODE                    21103 non-null  float64
 58   YEARS_BEGINEXPLUATATION_MODE         25888 non-null  float64
 59   YEARS_BUILD_MODE                     16926 non-null  float64
 60   COMMONAREA_MODE                      15249 non-null  float64
 61   ELEVATORS_MODE                       23555 non-null  float64
 62   ENTRANCES_MODE                       25165 non-null  float64
 63   FLOORSMAX_MODE                       25423 non-null  float64
 64   FLOORSMIN_MODE                       16278 non-null  float64
 65   LANDAREA_MODE                        20490 non-null  float64
 66   LIVINGAPARTMENTS_MODE                15964 non-null  float64
 67   LIVINGAREA_MODE                      25192 non-null  float64
 68   NONLIVINGAPARTMENTS_MODE             15397 non-null  float64
 69   NONLIVINGAREA_MODE                   22660 non-null  float64
 70   APARTMENTS_MEDI                      24857 non-null  float64
 71   BASEMENTAREA_MEDI                    21103 non-null  float64
 72   YEARS_BEGINEXPLUATATION_MEDI         25888 non-null  float64
 73   YEARS_BUILD_MEDI                     16926 non-null  float64
 74   COMMONAREA_MEDI                      15249 non-null  float64
 75   ELEVATORS_MEDI                       23555 non-null  float64
 76   ENTRANCES_MEDI                       25165 non-null  float64
 77   FLOORSMAX_MEDI                       25423 non-null  float64
 78   FLOORSMIN_MEDI                       16278 non-null  float64
 79   LANDAREA_MEDI                        20490 non-null  float64
 80   LIVINGAPARTMENTS_MEDI                15964 non-null  float64
 81   LIVINGAREA_MEDI                      25192 non-null  float64
 82   NONLIVINGAPARTMENTS_MEDI             15397 non-null  float64
 83   NONLIVINGAREA_MEDI                   22660 non-null  float64
 84   FONDKAPREMONT_MODE                   15947 non-null  object
 85   HOUSETYPE_MODE                       25125 non-null  object
 86   TOTALAREA_MODE                       26120 non-null  float64
 87   WALLSMATERIAL_MODE                   24851 non-null  object
 88   EMERGENCYSTATE_MODE                  26535 non-null  object
 89   OBS_30_CNT_SOCIAL_CIRCLE             48715 non-null  float64
 90   DEF_30_CNT_SOCIAL_CIRCLE             48715 non-null  float64
 91   OBS_60_CNT_SOCIAL_CIRCLE             48715 non-null  float64
 92   DEF_60_CNT_SOCIAL_CIRCLE             48715 non-null  float64
 93   DAYS_LAST_PHONE_CHANGE               48744 non-null  float64
 94   FLAG_DOCUMENT_2                      48744 non-null  int64
 95   FLAG_DOCUMENT_3                      48744 non-null  int64
 96   FLAG_DOCUMENT_4                      48744 non-null  int64
 97   FLAG_DOCUMENT_5                      48744 non-null  int64
 98   FLAG_DOCUMENT_6                      48744 non-null  int64
 99   FLAG_DOCUMENT_7                      48744 non-null  int64
 100  FLAG_DOCUMENT_8                      48744 non-null  int64
 101  FLAG_DOCUMENT_9                      48744 non-null  int64
 102  FLAG_DOCUMENT_10                     48744 non-null  int64
 103  FLAG_DOCUMENT_11                     48744 non-null  int64
 104  FLAG_DOCUMENT_12                     48744 non-null  int64
 105  FLAG_DOCUMENT_13                     48744 non-null  int64
 106  FLAG_DOCUMENT_14                     48744 non-null  int64
 107  FLAG_DOCUMENT_15                     48744 non-null  int64
 108  FLAG_DOCUMENT_16                     48744 non-null  int64
 109  FLAG_DOCUMENT_17                     48744 non-null  int64
 110  FLAG_DOCUMENT_18                     48744 non-null  int64
 111  FLAG_DOCUMENT_19                     48744 non-null  int64
 112  FLAG_DOCUMENT_20                     48744 non-null  int64
 113  FLAG_DOCUMENT_21                     48744 non-null  int64
 114  AMT_REQ_CREDIT_BUREAU_HOUR           42695 non-null  float64
 115  AMT_REQ_CREDIT_BUREAU_DAY            42695 non-null  float64
 116  AMT_REQ_CREDIT_BUREAU_WEEK           42695 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_MON            42695 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_QRT            42695 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_YEAR           42695 non-null  float64
 120  NAME_CONTRACT_TYPE_CASH_LOAN         48744 non-null  int64
 121  NAME_CONTRACT_TYPE_REVOLVING_LOAN    48744 non-null  int64
 122  CNT_DOC_TOTAL                        48744 non-null  int64
 123  RATIO_INCOME_TO_FAM_MEMBERS          48744 non-null  float64
 124  RATIO_AMT_CREDIT_TO_AMT_GOODS_PRICE  48744 non-null  float64
 125  FLAG_STABLE_INCOME_TYPE              48744 non-null  int64
 126  FLAG_RISKED_ORGANIZATION_TYPE        48744 non-null  int64
 127  NEW_AMT_REQ_CREDIT_BUREAU_WEEK       42695 non-null  float64
 128  CNT_PREV                             48744 non-null  float64
 129  AMT_PREV_SUM                         48744 non-null  float64
 130  AMT_PREV_SUM_DEBT                    48744 non-null  float64
 131  AMT_PREV_SUM_OVERDUE                 48744 non-null  float64
 132  AMT_PREV_MAX_OVERDUE                 48744 non-null  float64
 133  CNT_CREDIT                           48744 non-null  float64
 134  AMT_CREDIT_SUM                       48744 non-null  float64
 135  AMT_CREDIT_SUM_DEBT                  48744 non-null  float64
 136  AMT_CREDIT_SUM_OVERDUE               48744 non-null  float64
 137  AMT_CREDIT_MAX_OVERDUE               48744 non-null  float64
 138  CNT_ALL                              48744 non-null  float64
 139  AMT_ALL_SUM                          48744 non-null  float64
 140  AMT_ALL_SUM_DEBT                     48744 non-null  float64
 141  AMT_ALL_SUM_OVERDUE                  48744 non-null  float64
 142  AMT_ALL_MAX_OVERDUE                  48744 non-null  float64
 143  CODE_GENDER_F                        48744 non-null  int64
 144  CODE_GENDER_M                        48744 non-null  int64
 145  CODE_GENDER_XNA                      48744 non-null  int64
 146  AMT_ALL_SUM_MEAN                     48744 non-null  float64
 147  RATIO_ALL_SUM_OVERDUE_TO_INCOME      48744 non-null  float64
 148  RATIO_ALL_MAX_OVERDUE_TO_INCOME      48744 non-null  float64
 149  RATIO_ALL_SUM_DEBT_TO_INCOME         48744 non-null  float64
dtypes: float64(89), int64(48), object(13)
memory usage: 55.8+ MB

In [12]:
client_base.head()

,SK_ID_CURR,TARGET,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,...,AMT_ALL_SUM_DEBT,AMT_ALL_SUM_OVERDUE,AMT_ALL_MAX_OVERDUE,CODE_GENDER_F,CODE_GENDER_M,CODE_GENDER_XNA,AMT_ALL_SUM_MEAN,RATIO_ALL_SUM_OVERDUE_TO_INCOME,RATIO_ALL_MAX_OVERDUE_TO_INCOME,RATIO_ALL_SUM_DEBT_TO_INCOME
0,100001,NaN,N,1,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,...,595173.600,0.000,0.000,1,0,0,184644.000000,0.000000,0.000000,4.408693
1,100005,NaN,N,1,0,99000.0,222768.0,17370.0,180000.0,Unaccompanied,...,557213.355,0.000,4813.200,0,1,0,174319.875000,0.000000,0.583418,5.628418
2,100013,NaN,Y,1,0,202500.0,663264.0,69777.0,630000.0,NaN,...,-373892.625,171562.725,23153.985,0,1,0,379545.222857,0.847223,1.372088,-1.846383
3,100028,NaN,N,1,2,315000.0,1575000.0,49018.5,1575000.0,Unaccompanied,...,218010.465,70348.230,11250.000,1,0,0,129077.472000,0.223328,0.428571,0.692097
4,100038,NaN,Y,0,1,180000.0,625500.0,32067.0,625500.0,Unaccompanied,...,-29497.950,0.000,0.000,0,1,0,92605.500000,0.000000,0.000000,-0.163878

In [11]:
domain_features=['DAYS_BIRTH', 'CODE_GENDER_F', 'FLAG_RISKED_ORGANIZATION_TYPE', 
                 'RATIO_INCOME_TO_FAM_MEMBERS', 'FLAG_STABLE_INCOME_TYPE',
                 'EXT_SOURCE_2',
                 'AMT_ALL_SUM_MEAN', 'RATIO_ALL_SUM_DEBT_TO_INCOME', 'RATIO_ALL_SUM_OVERDUE_TO_INCOME', 'RATIO_ALL_MAX_OVERDUE_TO_INCOME']

In [17]:
id_client = 100028
client_base.loc[client_base['SK_ID_CURR'] == id_client, domain_features]

,DAYS_BIRTH,CODE_GENDER_F,FLAG_RISKED_ORGANIZATION_TYPE,RATIO_INCOME_TO_FAM_MEMBERS,FLAG_STABLE_INCOME_TYPE,EXT_SOURCE_2,AMT_ALL_SUM_MEAN,RATIO_ALL_SUM_DEBT_TO_INCOME,RATIO_ALL_SUM_OVERDUE_TO_INCOME,RATIO_ALL_MAX_OVERDUE_TO_INCOME
3,-13976,1,0,78750.0,0,0.509677,129077.472,0.692097,0.223328,0.428571

In [57]:
URL_data = 'https://drive.google.com/uc?id=1-bsOZer49Cz0g1xNK1ygk657k94Jilu3'  # URL Public
URL_client = 'https://drive.google.com/uc?id=1-ZX9AKIhO6rFqbcd3sOqdp3rPtZkD4QA'
URL_data = 'https://drive.google.com/uc?id=1-bsOZer49Cz0g1xNK1ygk657k94Jilu3'
try:
    data = pd.read_csv(URL_data, nrows=1000)
    data = data.iloc[:, 3:]  # Je supprime des colonnes de réplication des index (je ne sais pas d'où elles viennent mais pas grave)
    data.info(verbose=True, show_counts=True)
except pd.errors.ParserError as e:
    print(f"Erreur lors de la lecture du CSV : {e}")
except Exception as e:
    print(f"Une erreur s'est produite : {e}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame

In [51]:
URL_data = 'https://drive.google.com/file/d/1-bsOZer49Cz0g1xNK1ygk657k94Jilu3'  # URL Public
URL_client = 'G:/My Drive/DataScience/OpenClassroom/public/oc-pj7/data/application_test_features.csv'
URL_client = 'https://drive.google.com/file/d/1-ZX9AKIhO6rFqbcd3sOqdp3rPtZkD4QA/view?export=download'  # URL Public
URL_client = 'https://drive.google.com/file/d/1-ZX9AKIhO6rFqbcd3sOqdp3rPtZkD4QA/view?export=download'  # URL Public
URL_data = 'https://drive.google.com/uc?id=1-bsOZer49Cz0g1xNK1ygk657k94Jilu3'  # URL Public
URL_client = 'https://drive.google.com/uc?id=1-ZX9AKIhO6rFqbcd3sOqdp3rPtZkD4QA'
try:
    data = pd.read_csv(URL_client)
    data = data.iloc[:, 3:]  # Je supprime des colonnes de réplication des index (je ne sais pas d'où elles viennent mais pas grave)
    data.info(verbose=True, show_counts=True)
except pd.errors.ParserError as e:
    print(f"Erreur lors de la lecture du CSV : {e}")
except Exception as e:
    print(f"Une erreur s'est produite : {e}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Data columns (total 150 columns):
 #    Column                               Non-Null Count  Dtype
---   ------                               --------------  -----
 0    SK_ID_CURR                           48744 non-null  int64
 1    TARGET                               0 non-null      float64
 2    FLAG_OWN_CAR                         48744 non-null  object
 3    FLAG_OWN_REALTY                      48744 non-null  int64
 4    CNT_CHILDREN                         48744 non-null  int64
 5    AMT_INCOME_TOTAL                     48744 non-null  float64
 6    AMT_CREDIT                           48744 non-null  float64
 7    AMT_ANNUITY                          48720 non-null  float64
 8    AMT_GOODS_PRICE                      48744 non-null  float64
 9    NAME_TYPE_SUITE                      47833 non-null  object
 10   NAME_INCOME_TYPE                     48744 non-null  object
 11   NAME_EDUCATION_TYPE                  48744 non-null  object
 12   NAME_FAMILY_STATUS                   48744 non-null  object
 13   NAME_HOUSING_TYPE                    48744 non-null  object
 14   REGION_POPULATION_RELATIVE           48744 non-null  float64
 15   DAYS_BIRTH                           48744 non-null  int64
 16   DAYS_EMPLOYED                        48744 non-null  float64
 17   DAYS_REGISTRATION                    48744 non-null  float64
 18   DAYS_ID_PUBLISH                      48744 non-null  int64
 19   OWN_CAR_AGE                          16432 non-null  float64
 20   FLAG_MOBIL                           48744 non-null  int64
 21   FLAG_EMP_PHONE                       48744 non-null  int64
 22   FLAG_WORK_PHONE                      48744 non-null  int64
 23   FLAG_CONT_MOBILE                     48744 non-null  int64
 24   FLAG_PHONE                           48744 non-null  int64
 25   FLAG_EMAIL                           48744 non-null  int64
 26   OCCUPATION_TYPE                      33139 non-null  object
 27   CNT_FAM_MEMBERS                      48744 non-null  float64
 28   REGION_RATING_CLIENT                 48744 non-null  int64
 29   REGION_RATING_CLIENT_W_CITY          48744 non-null  int64
 30   WEEKDAY_APPR_PROCESS_START           48744 non-null  object
 31   HOUR_APPR_PROCESS_START              48744 non-null  int64
 32   REG_REGION_NOT_LIVE_REGION           48744 non-null  int64
 33   REG_REGION_NOT_WORK_REGION           48744 non-null  int64
 34   LIVE_REGION_NOT_WORK_REGION          48744 non-null  int64
 35   REG_CITY_NOT_LIVE_CITY               48744 non-null  int64
 36   REG_CITY_NOT_WORK_CITY               48744 non-null  int64
 37   LIVE_CITY_NOT_WORK_CITY              48744 non-null  int64
 38   ORGANIZATION_TYPE                    48744 non-null  object
 39   EXT_SOURCE_1                         48744 non-null  float64
 40   EXT_SOURCE_2                         48744 non-null  float64
 41   EXT_SOURCE_3                         48744 non-null  float64
 42   APARTMENTS_AVG                       24857 non-null  float64
 43   BASEMENTAREA_AVG                     21103 non-null  float64
 44   YEARS_BEGINEXPLUATATION_AVG          25888 non-null  float64
 45   YEARS_BUILD_AVG                      16926 non-null  float64
 46   COMMONAREA_AVG                       15249 non-null  float64
 47   ELEVATORS_AVG                        23555 non-null  float64
 48   ENTRANCES_AVG                        25165 non-null  float64
 49   FLOORSMAX_AVG                        25423 non-null  float64
 50   FLOORSMIN_AVG                        16278 non-null  float64
 51   LANDAREA_AVG                         20490 non-null  float64
 52   LIVINGAPARTMENTS_AVG                 15964 non-null  float64
 53   LIVINGAREA_AVG                       25192 non-null  float64
 54   NONLIVINGAPARTMENTS_AVG              15397 non-null  float64
 55   NONLIVINGAREA_AVG                    22660 non-null  float64
 56   APARTMENTS_MODE                      24857 non-null  float64
 57   BASEMENTAREA_MODE                    21103 non-null  float64
 58   YEARS_BEGINEXPLUATATION_MODE         25888 non-null  float64
 59   YEARS_BUILD_MODE                     16926 non-null  float64
 60   COMMONAREA_MODE                      15249 non-null  float64
 61   ELEVATORS_MODE                       23555 non-null  float64
 62   ENTRANCES_MODE                       25165 non-null  float64
 63   FLOORSMAX_MODE                       25423 non-null  float64
 64   FLOORSMIN_MODE                       16278 non-null  float64
 65   LANDAREA_MODE                        20490 non-null  float64
 66   LIVINGAPARTMENTS_MODE                15964 non-null  float64
 67   LIVINGAREA_MODE                      25192 non-null  float64
 68   NONLIVINGAPARTMENTS_MODE             15397 non-null  float64
 69   NONLIVINGAREA_MODE                   22660 non-null  float64
 70   APARTMENTS_MEDI                      24857 non-null  float64
 71   BASEMENTAREA_MEDI                    21103 non-null  float64
 72   YEARS_BEGINEXPLUATATION_MEDI         25888 non-null  float64
 73   YEARS_BUILD_MEDI                     16926 non-null  float64
 74   COMMONAREA_MEDI                      15249 non-null  float64
 75   ELEVATORS_MEDI                       23555 non-null  float64
 76   ENTRANCES_MEDI                       25165 non-null  float64
 77   FLOORSMAX_MEDI                       25423 non-null  float64
 78   FLOORSMIN_MEDI                       16278 non-null  float64
 79   LANDAREA_MEDI                        20490 non-null  float64
 80   LIVINGAPARTMENTS_MEDI                15964 non-null  float64
 81   LIVINGAREA_MEDI                      25192 non-null  float64
 82   NONLIVINGAPARTMENTS_MEDI             15397 non-null  float64
 83   NONLIVINGAREA_MEDI                   22660 non-null  float64
 84   FONDKAPREMONT_MODE                   15947 non-null  object
 85   HOUSETYPE_MODE                       25125 non-null  object
 86   TOTALAREA_MODE                       26120 non-null  float64
 87   WALLSMATERIAL_MODE                   24851 non-null  object
 88   EMERGENCYSTATE_MODE                  26535 non-null  object
 89   OBS_30_CNT_SOCIAL_CIRCLE             48715 non-null  float64
 90   DEF_30_CNT_SOCIAL_CIRCLE             48715 non-null  float64
 91   OBS_60_CNT_SOCIAL_CIRCLE             48715 non-null  float64
 92   DEF_60_CNT_SOCIAL_CIRCLE             48715 non-null  float64
 93   DAYS_LAST_PHONE_CHANGE               48744 non-null  float64
 94   FLAG_DOCUMENT_2                      48744 non-null  int64
 95   FLAG_DOCUMENT_3                      48744 non-null  int64
 96   FLAG_DOCUMENT_4                      48744 non-null  int64
 97   FLAG_DOCUMENT_5                      48744 non-null  int64
 98   FLAG_DOCUMENT_6                      48744 non-null  int64
 99   FLAG_DOCUMENT_7                      48744 non-null  int64
 100  FLAG_DOCUMENT_8                      48744 non-null  int64
 101  FLAG_DOCUMENT_9                      48744 non-null  int64
 102  FLAG_DOCUMENT_10                     48744 non-null  int64
 103  FLAG_DOCUMENT_11                     48744 non-null  int64
 104  FLAG_DOCUMENT_12                     48744 non-null  int64
 105  FLAG_DOCUMENT_13                     48744 non-null  int64
 106  FLAG_DOCUMENT_14                     48744 non-null  int64
 107  FLAG_DOCUMENT_15                     48744 non-null  int64
 108  FLAG_DOCUMENT_16                     48744 non-null  int64
 109  FLAG_DOCUMENT_17                     48744 non-null  int64
 110  FLAG_DOCUMENT_18                     48744 non-null  int64
 111  FLAG_DOCUMENT_19                     48744 non-null  int64
 112  FLAG_DOCUMENT_20                     48744 non-null  int64
 113  FLAG_DOCUMENT_21                     48744 non-null  int64
 114  AMT_REQ_CREDIT_BUREAU_HOUR           42695 non-null  float64
 115  AMT_REQ_CREDIT_BUREAU_DAY            42695 non-null  float64
 116  AMT_REQ_CREDIT_BUREAU_WEEK           42695 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_MON            42695 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_QRT            42695 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_YEAR           42695 non-null  float64
 120  NAME_CONTRACT_TYPE_CASH_LOAN         48744 non-null  int64
 121  NAME_CONTRACT_TYPE_REVOLVING_LOAN    48744 non-null  int64
 122  CNT_DOC_TOTAL                        48744 non-null  int64
 123  RATIO_INCOME_TO_FAM_MEMBERS          48744 non-null  float64
 124  RATIO_AMT_CREDIT_TO_AMT_GOODS_PRICE  48744 non-null  float64
 125  FLAG_STABLE_INCOME_TYPE              48744 non-null  int64
 126  FLAG_RISKED_ORGANIZATION_TYPE        48744 non-null  int64
 127  NEW_AMT_REQ_CREDIT_BUREAU_WEEK       42695 non-null  float64
 128  CNT_PREV                             48744 non-null  float64
 129  AMT_PREV_SUM                         48744 non-null  float64
 130  AMT_PREV_SUM_DEBT                    48744 non-null  float64
 131  AMT_PREV_SUM_OVERDUE                 48744 non-null  float64
 132  AMT_PREV_MAX_OVERDUE                 48744 non-null  float64
 133  CNT_CREDIT                           48744 non-null  float64
 134  AMT_CREDIT_SUM                       48744 non-null  float64
 135  AMT_CREDIT_SUM_DEBT                  48744 non-null  float64
 136  AMT_CREDIT_SUM_OVERDUE               48744 non-null  float64
 137  AMT_CREDIT_MAX_OVERDUE               48744 non-null  float64
 138  CNT_ALL                              48744 non-null  float64
 139  AMT_ALL_SUM                          48744 non-null  float64
 140  AMT_ALL_SUM_DEBT                     48744 non-null  float64
 141  AMT_ALL_SUM_OVERDUE                  48744 non-null  float64
 142  AMT_ALL_MAX_OVERDUE                  48744 non-null  float64
 143  CODE_GENDER_F                        48744 non-null  int64
 144  CODE_GENDER_M                        48744 non-null  int64
 145  CODE_GENDER_XNA                      48744 non-null  int64
 146  AMT_ALL_SUM_MEAN                     48744 non-null  float64
 147  RATIO_ALL_SUM_OVERDUE_TO_INCOME      48744 non-null  float64
 148  RATIO_ALL_MAX_OVERDUE_TO_INCOME      48744 non-null  float64
 149  RATIO_ALL_SUM_DEBT_TO_INCOME         48744 non-null  float64
dtypes: float64(89), int64(48), object(13)
memory usage: 55.8+ MB

In [30]:
data.head()

,SK_ID_CURR,TARGET,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,...,AMT_ALL_SUM_DEBT,AMT_ALL_SUM_OVERDUE,AMT_ALL_MAX_OVERDUE,CODE_GENDER_F,CODE_GENDER_M,CODE_GENDER_XNA,AMT_ALL_SUM_MEAN,RATIO_ALL_SUM_OVERDUE_TO_INCOME,RATIO_ALL_MAX_OVERDUE_TO_INCOME,RATIO_ALL_SUM_DEBT_TO_INCOME
0,100001,NaN,N,1,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,...,595173.600,0.000,0.000,1,0,0,184644.000000,0.000000,0.000000,4.408693
1,100005,NaN,N,1,0,99000.0,222768.0,17370.0,180000.0,Unaccompanied,...,557213.355,0.000,4813.200,0,1,0,174319.875000,0.000000,0.583418,5.628418
2,100013,NaN,Y,1,0,202500.0,663264.0,69777.0,630000.0,NaN,...,-373892.625,171562.725,23153.985,0,1,0,379545.222857,0.847223,1.372088,-1.846383
3,100028,NaN,N,1,2,315000.0,1575000.0,49018.5,1575000.0,Unaccompanied,...,218010.465,70348.230,11250.000,1,0,0,129077.472000,0.223328,0.428571,0.692097
4,100038,NaN,Y,0,1,180000.0,625500.0,32067.0,625500.0,Unaccompanied,...,-29497.950,0.000,0.000,0,1,0,92605.500000,0.000000,0.000000,-0.163878

In [34]:
data.sample(1).to_numpy()

array([[335944, nan, 'Y', 1, 1, 81000.0, 312840.0, 22761.0, 247500.0,
        'Family', 'Commercial associate',
        'Secondary / secondary special', 'Married', 'House / apartment',
        0.006296, -11336, -1894.0, -103.0, -1382, 16.0, 1, 1, 0, 1, 0, 0,
        'Core staff', 3.0, 3, 3, 'MONDAY', 11, 0, 0, 0, 0, 1, 1,
        'Trade: type 7', 0.549511457430798, 0.3568402042054893,
        0.3672910183026313, 0.0928, nan, 0.9891, nan, nan, nan, 0.2069,
        0.1667, nan, nan, nan, nan, nan, nan, 0.0945, nan, 0.9891, nan,
        nan, nan, 0.2069, 0.1667, nan, nan, nan, nan, nan, nan, 0.0937,
        nan, 0.9891, nan, nan, nan, 0.2069, 0.1667, nan, nan, nan, nan,
        nan, nan, nan, 'block of flats', 0.0225, 'Stone, brick', 'No',
        0.0, 0.0, 0.0, 0.0, -1367.0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1, 0, 1,
        27000.0, 1.264, 0, 0, 0.0, 2.0, 183015.0, -17583.930000000026,
        0.0, 0.0, 11.0, 2835238.14, 1701742.5, 0.0, 0.0, 13.0,
        3018253.14, 1684158.57, 0.0, 0.0, 1, 0, 0, 232173.31846153847,
        0.0, 0.0, 20.79208111111112]], dtype=object)

In [41]:
import requests
import pandas as pd
import io

URL_client = 'https://drive.google.com/file/d/1-ZX9AKIhO6rFqbcd3sOqdp3rPtZkD4QA/view?export=download'  # URL Public

try:
    response = requests.get(URL_client)
    response.raise_for_status()  # Lève une exception pour les codes d'erreur HTTP (4xx ou 5xx)
    df = pd.read_csv(io.StringIO(response.text)) #io.StringIO permet de lire le contenu de la réponse comme un fichier
    print(df.head())
except requests.exceptions.RequestException as e:
    print(f"Erreur lors de la requête : {e}")
except pd.errors.ParserError as e:
    print(f"Erreur lors de la lecture du CSV : {e}")
except Exception as e:
    print(f"Une erreur s'est produite : {e}")

Erreur lors de la lecture du CSV : Error tokenizing data. C error: Expected 1 fields in line 3, saw 2461

In [50]:
import chardet
import requests
import pandas as pd
import io

url = 'https://drive.google.com/file/d/1-ZX9AKIhO6rFqbcd3sOqdp3rPtZkD4QA/view?export=download'  # URL Public

try:
    response = requests.get(url, stream=True)
    response.raise_for_status()

    rawdata = response.raw.read(50000) # Lire les 10000 premiers octets pour la détection
    result = chardet.detect(rawdata)
    encoding = result['encoding']

    print(f"Encodage détecté : {encoding}")

    df = pd.read_csv(io.StringIO(response.text), encoding=encoding)
    print(df.head())

except requests.exceptions.RequestException as e:
    print(f"Erreur de requête : {e}")
except Exception as e:
    print(f"Autre erreur : {e}")

b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x00\xec}\xe9r\xe3F\xb2\xee\x7f?\x05\x87\x11g\xba\xfb\x0cHa_$\xcb\x1e\xedbk\xdf[\x92\x15\x0c,E\x12"6a!E\xb5\xfb]\xce\xb3\xdc\'\xbb\x99\x05\xa0\x00\x82l\xaa}\x8f\xe7\xcf\x8d\xb6gh\xa2P\xa8%+3\xbf\xac\xca\x0f\xd4\xaf\xff\xd8=\xdb\xb9\xbe?\xdfk\x8dR\xdf\xfb\xed\xd7\xe2\x93\x98\xceo\xbf&v\xecFi+\x08\x03\x9bl\xb6G\xbdm\x99\xa4\xf7\xfb\xfd\x03\xd9\xea\x93\xe9Nx\xe8%/\xd3\xf6o\xad\xa9\x1b8\xe1\xf4\xf1C\x7f\xf7\xb2w\xbb\xd7\xbf\xed\xed\xdd\xed]\xf6\xed\xd4\xf5\xdd`\xf8\xe1i\xf3\xeb\xb7\x8d\xd6\xafkyc\xbf\xfd\xea\x93\xd4l\x05\xa6\x0f-\x0e\xc3p\xe8\x91v\xcb\x0e\x83\x94\x04\xe9f;\x08\xd3\xd8\x0c\x12\xcfLI\xbb\xa89J\xd3\xa8C^2w\xb2\xd9\xfe\xd2\xb9\xd9\xea\xec\x84~d\xa6\xae5\xf7`oo\x938C\xb2\x01O%\xe9\xcc#\xe5\x98M\xcd<\x11\xceB\xedX\xbd\x9d\x1e\xbd>\xf7\xb2\x97\xce\xf4\x14\xc6\xfc\xef\x01<\xd9\x19\x986\xf9Z|\xf3]o\xb6\xfe\xe12\xb4\xc24\xfc\xb0A\x0biK\xebnjz\xae\x9d\x97L\x89;\x1c\xa5\xeb2\xcfo$\xb1\xbd\x9e\xc5\xde\xc7\xb55\xbc\x93t\x87I\n\xa3\xb2\xbbv\xe8\xaf%k1mgm"\xe8kG\xfbg\xe3\x9d\xe0e/3\xc4\xfdX8\xc9\x14\xe1\xb5\xd7{\xb3\xbbi:\xf84\x08c\xdfL?~H\xe3\x8c\xa4\xb3\x88|\xf8\xb4\xf1\xed/\x0c-\xc0\xc7\xbd\xb9\xa1I\x7fqh^mh\xfe\xd5\x8d2\xd8\xde\xb6\x8d\xff\xd0\xd8\xfe\xaa\xd8\xfc\xba\xd8d\xff\xf5\xfc?4.\xe5\x7f#\xb3\xbd\x1b\xe3?)3\xed\x7f3\xb6\xbb\x1bo\xf5\xd8\xc0*\xb1\xe39\xa3\x8c\xc9\x80\xc41\x89k\xd6\x15\xc6\xee\xd0\r\xc0\xb6R7\x85\xdaf\x14\x81E\xc0\x10\xc2\xa0\x9f\x92$\xed\x0f\x88\x99f1I\xbav2iuZ\x07\xd4\xac\xff\xcf\xff\xec\xc6\xee\x84\xfc\xba\x96?\xf4\x83\xce\xe4\x97\x16\xfbg\xb9[\xe9\xdd\xf6\xae><\xb56[Nhg>\x0c\xaf;q\x13\xd7r=7\x9d]\x81\\\xc8\x06k\xa2\xe1s\xa28\x8cH\x9c\xce`>\xc3u:\xa8\xda\x14W\xce\xa9\xbd\xb4\x05\x90a\xbd\x81\x18\x96\xc4#K\xab&nJ\xfa(\xddZ\xfd\\H\xad\xdd\xd0N\x96>\x03\x0b^\xab\x8d^0Y_[sP\xa4\xdd\xdco\xd2\xf5\x1f\xb8\x1eYs\xd6\x84\xce\xc3\x17c\xeb\xa87:S\xe3\xfd\x17\xcbv\xa4\xe4\xec\xc5\x89\xa4\xf8<}\x18\xef\xca\x17[k\x13\x97L\x7f\'\xafQ\x18\xa7\x9b \xd6\xc0\x0bM\xe7\x9f\xa6\x1fmdI\xb4I|\x8b8}\xd4Q+\x0c\xc70\x1e\xcf\r\xc6\xad\x98x\x9b\xedd\x04O\xd8Y\xdara0\xed\xd6\x08\xd4\xa3\x1aN\x92xs\xda\xe8\xfa\xe6\x90$k\x168q\x07|\xff\x1a\xcc\xc8\xc9\xectMx\xcdG\xde\x17y\x91\x7f\x91\xfb\x92\xe8D\xdd(\x18\xb6\xff.\x8cy\xfc`{\t@\r\xc8\x8f\xea94\xd6\r\xc2\xe9\xc7Ou\xe4\xa9M\n\xb5>\x19\x11\x926gTX\x18\x15\xb0\x19\xb9\t\x9d\x96\x9d$\xbf\xe7f\xbb\x99/\xdb\xbf\xae\x00\xa5\xfa\xa1\xe7\xa0\xbf\xe5\xc0\xafq\xe0C8\xb0\xd5\xf6{\xc0\xf3C\x83\x98N\xa7sb\xed\xaf\x81z&\x1d\\k\\F\xb8N\x92\xb5\xf1\xe6\\aw\xd2\x1d\xf2\x82\xbbu\xf7&\xc6\xa7{\xdd\xe3\xee]\xf7l\xcd\xf47\x0f\xb6\xa6k\xce&\xbf\x16\'\x9b[g</\x19\x99\x10\xeb\xb7\xea\xb3\x14i\xe4\xf3\xb5\x10\xf4le4\x1b\xcb{\x9fO\xaf\xfb\xc3v\xcb1S\xb3\xe3:\x9b\xed\xbe\xed\xfd\xe0d~L\x80bC\x82\'`\xaa\xb1kz\xff\xea\x81^%\xebSpv\xffF\x80@gL\x05\xb9 \xa3\xf7\x06\xf3\xf7i\x12yO\x93\x8a\xae*a\r\x9d\xf6{\x1d\xe7\xfdv\xefz\x0f\xfd\xa1\x17Z\xa6\xd7\xc7\xc7\xc1\x91}m__\xed\xa6\xb7\xed\xf5\xf6\x7fu\xff\xdd}|\x0c2\xcf\xe3\x1e\x1feEUeY\xd58z=0\xbd\x84\xe4_\xab\x8f?\xda\xce\x97[\xfd\xca\xf9\xa3\xfd\xc4\xd1\xfa\x82 i\xb5\xfb|W\x99\xab\xbd\x95>_\'\xa4\xac-\xe9\xba$\xe7\xb7\x10\x13\x16\x1b\xbf\x98\x043\xd9b\x8d\x8b\no\xac\x1c\xcc\xe0x\'\r\x06e}E\x17\x0c}e\xfd\xc9\xe4^ql\xd6>o\xc8\xe2\xaa\xe1\x1c9\x07\xf7\x11\x1b\x8e\xa2\x89\xaa\xb4\xb2\xf9\xed\xd9\xde\xdek5|\x99\xd7W\xcb\xf2\xb33z\x15Y}Y\x175ee\xfd/\xcal\xf6V\xcdV\x04\x0f\xb0\xaa:\xb9\x18\t\xcfL:\xb0\xb2\xe5l\xe7\xda\xec\xdc]\xb5\xc0K\xff\xe3\x8fvY\x14\'\xf1\xeb\x01\x93\x92&\xa8\x8a\xb8\xb2\x9f\xe02\xd1\xecJ%dE\\=\xed\x8b\x03\xffx\xbfV_\xd7V\xd7\xbf<VvfL\x894I\xd1\xf5\x15*7\x10\xe3\xcc\x1fT\n\xaa\xf3\xabG\xdf\xe3\ro\xe0\xd4uh\xb5\xce\xdd|y9\x90\x98tdA\x97V\xeb\xdc\xe0\xf8\xfcuT\x8dG\x16\xd4\xd5\xab\xb6\xe7\xba\xa1\xca\x9a\x97$e\xf5p\x0e\xec\xd7\xec\x88T:dH\xab\x9b\xcf\x8eNw\xc29a\xaaKV\xf4\xf0.H^N^\\>\xc9\x8e\x84\xd3\x87X<\xe2/N>?\x0c\x8e^\xbeTz\x12E\xa1\xbf\xcff&\x19\x8a,\xac\xec\xfa\xf8\xd0\r\xdc9\xd7\xb1\xa4\xeb\xe3\xdd\xfd/\x91\xbb\x9b\xf0\xdb\x814\xb4\xee\xe4-\xfba\x87\xbf\xdd\x93\xedC\xc7\xa9\xba\x1e\xec{\xbc\xc0&\xc1\xab\xc6j\xc3\xbc\xd5\xee \xe0\xa8\xec^5V\x0b)\x9c\x1c\x1d&\xac\xbe&\xbe\xa7\xd1\xc7\xbd\xa3\xed\x98\tU\x91Ec\xb5$\xe2\xd1\xb9\x92U~K\x92Ea\xa5\x1f\x12w\xb4\xd0\xa9\xd6L\x97\xd5\x95\xcd\xdf\t\xc1\xfe>\xa9\x19\xbed\xacj\xfe \xfc\xbcsiWnN\xd6\x84f\xa5z\xf5\xf1\xc9\xa5\x12Au\xee\xf1\x8f\xf6\xe3\x13<V<g\xc0\xc8Vu\x13\xbd)\xbdj\xd2\xa8y\xdab\xa5\x0b1s\xa2\x81,\x0ek\x9awu%\'\xd7\xf7{Z\xb5\xfc\x99c?\x8f\xcb\x96DA\x15V\xdb\xc8\xf9`\xdc\x8b\xab\xd5\x17\xdfq\xcbA/;\xdfe\xe2\x83\x07\xf4\xd5\x16~2\x1c\\+L|\xaa\xa6\xadv8\xe1\x9di\x0c\xad\xba\x1cV+\xef\xec~\xac\xdcV\xab/\x1b\xef\xa0D\xb2}3\x1aT\xcb)\xa9\x82\xd2\xacT\xaf\xeeM\xf7y\xdeYXNMP\xf8\xd5Z\xf6l\xec\x8e*G"\xe8\xe2;R\xba\xd8\xff\x1cTR\x95E\xf9\x1d1\xc9\xa3\xa3\x176m\x19\x8c\x9c_\xa5]\xd9\xfd\xf3\xf9]e\xe2\x82\xf8N(\x10F#\xb1g\xd5lD\xae+\xbd\xd4\x15d\xa1\xf4\xbc\xc5\x13\xfb_\x84\xfd\xe3\x9aV\x18\xab\xc7\xef\x1e\xfaWwv\xbd\x03\x88\xdb\x17\x00\xb8\xa8\xfcje\x07\x97\x95\xff\x10\xd4\xd5\n}\xb8\x93\x89\xb3Am,\xd2\xea\xb1D\xf2d\xeb\xa2Bt\xde\xd0V/\xed\xf1\xcd\x9b\x928T\x17\xfeh\xefl\x9d\\\x1dn\xf3\xce\x9bv\x16\x9eN\xcf\xd4\xe8B\xdf\r\x15\xf9x\xcb\xb8\xce\xb6\xad#s\xfb\xe2L\xde\x9b\x9eO\xe2\xcb\xbd?\xfe\xc8 \xe0\xa7\x0f>\xb5\xb9vp1\xdb\xdak\xaf\x7f\xfd\xf6mc!\x92\xfd_\x07\xcd\x8e;X\xbe\xff\xfa\xab]\xf5a_\x9f\xf4\x07\x9e9\xec\x03>\xa5\xb0C\xd8\x850y\xf3k\x1b\xcb;\xa6\xeb%\x10(\xd3:6\xec\xbf`Z\xb4|0uXy0(K\xed\xb8\xaa\x1c\xc3\r\x8f\xdd\x88:i\xd4^WY=z\xa9\x94\x8d\x91NL\xda\xebby\xe9U\xdf=\xc1\xb3\xdb\xebru\xe5C\x07\'\x97We\xc3\x9e8w_\xa4\xf7\xb7/o\xaa\xfbi{\x9d//\x12\xa7\xbd.\x15\x17!\xec\xf7\xd7\x85\xe2"\x199AU/\x1d\x8c\xa0\x95\xb2\t\xd8\x0bA\x1b\xd4\xec\xdan0\x08\xfb\x91\x19\x9b~\x82\x0b[\xd6\xb0\x9dQY#/\xf0\xccd\n#\xc9\xf5\xab(3\x9d\xc5\xa2\x88\x96\xd5\x9f\xb4\x9d\x85"g\xb1\xadee^\xb0\xa4^\xb8X\xe6/\x19\x9b\xbfX\x14,\x8e-t\xa2\xc5z\xa1\xb5X\x16\xd9\x0beS\xf7\r\xca\x17\x9a\x8c\x12\xbb\xf9\xecB\x9dxTo\x8d$N\x08U\x12\\\xcbz\xaddq\x18\x89\xeb4\x9aJ\x16\x1aO\x97<\x17\xba\xee\xe2 \x06\x83$\xb0\x9b\xc5>\\\n\xb9\xda\x84I\xc7\x89F\xa8S<\xfcS\x15%Pd\x18|\xa9[v\x14\xd7Z\x08qy\xb3t\x107F0!\xae\xc9\x8a2j\x82\xa0\x8ev\x96\xa4\xa1O\xe2>=\n[o\x9f\xee\x96:\n\x8b\xd0\xf3oP\xa3\xbf{T\x84\xf5\xd6\xe0\x8b\x1f\x06k\x01I\xed\x11\xb1\xc7\xdd\xa1\xcbl\x97\xd8\x99i\x8f\x1a\xe3\xb0mwA\xa6\xf3\x056\x81\x82\xafm\xf8x\x04\xccT\x05U48\x81\x0784\x04U\xe54A\xd2a\xdf\x08\xae\xdfPE\xd8\xdf\txO\xc3\x08\x91\xe7\x0cY\x125\x15\xb6\x1b\x8a\xc6k\xbaA\x1fS\x01wD\x1e\xbf)\x02\x84\xf2:\x07\x11=l\x84U\x91>\x07\x0f\n:\xb4\x89u \xceW\xe0\x1b\x9f7\xa9\xc0N\x81W\xa0\x17I\xc3p\x12\xda\x86\x9d\x0f\xb4\xcb\x19\x06t\xa2+\xf9\x98`\xcf(Cw\xbchh\x92&Cm]\x14u\xbd(\x11x\x19\x9a\x86xA\x915x^\x114\xf8\x17\x1b\xc2\x96x\xec\x15\xda\xd1\xb4\xbciUU\xe0\x8b.HP\x0f\'\x02\xeb+\xd3\x81\xe8\x00.\x06\xd6VD\x08S\x15\xfc"\xcb\x9a\x8a#\x92!\xe0\x87\xd8\xc5P`_\x8f\xc7\x06\xd0\xa3\x06#(\x84d(\xb4W^\xc3x\xc5P\x04A\xd4yl\x1a\xa6,\xc2FA\x81\x11\xeb<\nM\xd7\xe8\x8e\x11\x86\x01\x9b5\x88\xfc\xb0\x07\x8c\x02s\t\xc1\x02((P\x19K\x0cx\\\x94e\x19o\xc9\xba.\x83d\xb1wA\xa0\xf3\xc1\xa9\x1b2T\x12q\x808yU\xd4\x05Q\x04\xb9\xc8\x9a\xc8C\x0c\x0f\xedH:\x04\xcf\xf0\x90$\x0b\x10\xde\xe6\x92\x86\x88\x90N\x15\x96\xd3\xc0\x85\x11\xa1\x0fC\x80\xee\x14\x897t\x05\'\x04\xcf\x81\n\xe4B\x83\xaeq\xf6\x92\x8c\xf2Px\x18+h\x04\xce\x0c`\x98\xd7p\x85T]\xc3\xd3<A\x07\xd9\x19\n\xb6m\xc8 \x1c\x9c$,?H\x19\x05b\xc0V\xd0\xa0\xb2\x96`\x9fG\xe7\xa8\xc9(*\x1e\x04A\xebJ\xa0\x03\xb0d(\x10UT$*<\x14$\xceL\x01\xe1\xd1Q\xd3\xbeh\x1f\x8a"\xf2\xb9l\xe0\x1e\x88\x93JI\xe6\xb1_\xfaM\x83\xa1\xa2\x98u\x94\x06mC\x84\xc1`?\x8a$\t*j\r\x84\x1e\xa8c\xb2\x01\xab/h\xa8\x90"\x84j\xa8\xec\xb2\x04\x0f\xd0vD\x08\xc6d\x1c\xae\xa2\x1b\xf9"\xf1\n\xaf+TH`\x08t\x060&\xd0G\x90\x8d \xa1\xd8`I\xa0e\x01KD\x08\x905\\~p!\x92L\xeb\xc2\xca\xe6\xb6\x02bT\xd0\x1cDP?\x8d\xae\x9f\xaa\xe1<@qE\x9c\x1fJ\x8d\x87@S\xa3%\xb0\xa2P\x07\xd4S\x80\xb9\xe1-\\G\x94\x96\x01\xf1\x93\x8a\xb2\x11y\xb0Z=75\xd4P|N\x80%\x11\xa8\xa9\x80\xcd\x8a(SP\x15\r\xf6\x9b0X(\xa0\x16\xa2\x81U\xe9*\x95\x10\x8c\x1c\x9b\x84q(\xb4I\x01\x06\xa4(h+\xa0\xc0\x85\xde\x80\x02\x802@\x03\xb0\x94T7\x14\x01-\x02%k`\x93`\xf4\x06\xf4\xaaR\xcb0@z\x8aL\x07\xa7BC*U7Q\xd5Aq\x14\x1e[\xd4q\xe20Fj\xb5\xb0\xda:\xe8\x15\xea\x14\xec\x12u\xea+x\xd0N\xba\xde:\xd4\xd6t:\x03\x90\x14J\x19tT\xc3\x15\x85\x89i\x8aJMI\x02\xdd\x13\xf2\xf5\x07w%\xe1P`\xbe\x92\x9c\xaf\xa9\xa1R\xad\x82M\x88J\x85*I\xa2D\xf5^\x00\xdd\xe6s3\x03\t\xe0\xe2\xea\xba\x08\xde\x01\x07\x00Z#)\x85\tjT?a\xff\x8d\xdaH\xd5E\xc2\xb5\x14\x05A\x95t\x95\x96\x88T\xa34\xf4\x1e\x06\x9d\x9a\x92\xab\x14\xc8\x18\x84\x91\x0f\r6\x1b|\xee.A\xaa2\n\x0e\x96Y\xc1\x99H\x02\xb4F\x15X\xd1\x14\x85N\x0e$ \x81\xe5\xa0\xb7\x93\x04I\xcc\xbb\x83M.\xca\x8b\xfa\x00\xbat\xe0\x1c\xe8b\xa2\xca\x81p`yuTT\xb4\\^E\x8d\xa1.\r\xa2s\xfa<8)\tg\t\xae\x11\x9cW.8\x10\x03~\xd1d^\xca\x05\x0f\xad\xd2\xd9\x82\x98\xe9l\rQ\xcf\x17W\x96\xf0h\x10]\x01\xb8r\x81b\x03H\x10\xfd\r\xb8&\t\xab\x00.H::20\x08C\xc9\x1d\x90!PO\x04v\x83\xb6\r\xea\x03b\xcf=\x03xd-\xd7Z]Q\xb0=]\x82\xea\x98#\x80]\xb9\xc4\xa3\x03\xa0\xc8$\x94\xc8D\xcd\x06\x91I\x11\x0bd\x92\xa5\x12\x99\xd0\xferd\x12JD\x12D\x86H|\x81HT\'sD\x92\nD\x12\xc5\xc2?\x8a\xbaQ \x11Z,E"E.\x90(\xef\x87"\x91\\ \x11\xc0d\x81DB^\xc2\xd3\x15A$B\xdfK\x91\x88\x9a\x10"\x91\\8UT\xd7\x1c\x89d\xa3@"Y*\x90H\x92J$\xd2\x8ae\x03\x95-\x90\x08\x07B\x91H\xd5\n$\xa2\x06\x8bH$\x14B1h\x8b\x80D\xd4\xdf\xa2\x03E{\xcf\x91H\xe4)\x12\xc1<\n$\xca\x87\x01H\xc4K\x05\x12\tR\x89D\xd8\x0eE I-\x11\x08$\x99#\x10\x9d\x07j\x1fh}\x8e@\x82Z \x10u7\xe8su\xa9@\x1eUa\xc8\xc3\x97\xc8\xa3\xcb\x05\xf2\xe8T?\x10yd\xbe@\x1e:m\x8a<|\x81<\x8aV \x0fu3\x80<tn\x88<\xaa!\x16\xc8\xa3k%\xf2\xd0I\xc12k\x86V"\x8fP \x8f$\x16\x88C\xeb \xe2\xa8R\x818\xb2R \x0e\r$(\xe2\xe4F\nu\r\xadD\x1cQ/\x11G\xd2\x19\xe2\x88%\xe2P\xa8D\xc4)P\x0b|\x07_ \x0e\x9a\x10E\x1c\x1aL \xe2\xf0F\x814\xb9_E\xa4\xe1u\xea\x8d\xc0{\x96\x00C\xcd\x1c\x01FU\x0b\x80\xd1\xe4\x02`x\xb5\x00\x18U\xcf\x01\x06\x85\x93\x03\x8c\xc0\x00F*\x00\x86\x06s\x080\xd4\xb8\x11`x\xad\x00\x18\xc9(\x00\x06\xac;\x07\x18X\xf0\x1c`4\xa9\x04\x18\xbe\x04\x18M.\x01\x86z\\\x04\x18^-\x00FP\n\x80\xd1\x95\x02`\xa8\xc3E\x80\xd1\xf8\x02`\xa8\xbdQ\x80\xe1K\x80\xc9\x036\x98\x88!\x96\x00#\xaa%\xc0\xf0%\xc0\xf0%\xc0\xf0\x05\xc0P\x85G\x80\xa1\xd8O\x01F\xceWG\x04\x93\xe3\x0b\x80\xd1\xd4\x02`\xa8\xa7\xa7\x00#\x94\x00\xc3\x17\x00S\xc4\xbcX[*\x00FV\x0b\x80Q\xc4\x12`\x84\x02`t\xa9\x04\x18Y)\x00FT\x0b\x80)\xb0R\x86\x9e\n\x80A\xd0\xa5\x00#\x8b%\xc0\xf0Z\x010\x14"\x11`r\x97\x8f\x00C\xd5\x91\x02\x0c\xcf\x80E(\x01E(\x00E\x12\n@Q\xa4\x12P4\xa5\x04\x14\x1a\xf5P@\xe1\x0b@\xc9\xe3\r\n(R\t(B\x01(\xa2\xcc\x00E,\x00\x85\x8a\x05\x01%GKP1E.\x00\x85\x86\xe6\x08(\xa2^\x00\x8a\xa2\x95\x80"j%\xa0\xf0\x05\xa0\xd0 \x99\x02\n_\x00\x8a\xac\x94\x80\xc2\xe7\x80\xa2\x8a\x05\xa0hF\x01(\xbcT\x00\x8a$\x15@\xa2i%\x80\x08\x05\x80\xe4q#\xb8\xa6\xc2\xc0e\x88\xb6J\x00\x91\xa5\x02@t1\x07\x10\xd1\x90\x9f`\xef5\xa0\'9\xe56\xe8u0\x99\xdf\x07\x99\x91\xdb\x19\x93\xd9\xdc\xb1\x80\x1f\xd9/\x93\xe6\xfe6\xb6R7m\x94\xa5I\x184\xeb\r\x06A\xb4\xa4h\xc0\xca\xac\xcc\xf5\x9cc\xd3"\xb8\xeb\x9bOM\xa7\xe4\xd5\'\xaf\x98\xfc\x07\xbd\x17\xd4\xae \xf4#\xbe\xdc\xe8%\xa3p\xdaw\x88\x95\xe1\x81\xcf l\xf4\xe1\xf8\xde\xa0y\x88\xe07\xc6\x16\xfbtG\xba\xbb\xb7\xbfus|\xdd?=\xeb_\xee]_\xdeC\x07a\xe0xV6\xb7\x0f\xc5\'j\x04\n\x1c\x05e&4j5x\x16P\r\xa6\xf4N\xa5\x9c\x8cQ\x9d\xd3\xc4\xb8\xd7\xae\xed\xce\x87\x89\xef\xd4\x1e\x9f\x86\xf18\x89L\xbb\xd1\x0f\xad\xea\xda\x8e\x0f\xab\xf2\xf8Tn\xec]\x10>H\x8fg\x9by,\x1b\xe4\xbb\xfb\xf2:q\xf1<\tB\x05\x8d\xad8\x96\xd4E\xe5\xbbV{\x1d \x10\xec\xa2\xd6\x0eT\x12\xd1\xd7\x17\xe2\xc4k0\x82\xf2\x14\x8b\x8c\xec\xc6\xe1\x83\xeb\xda\x8d\x93\x98\xa1?h.S`\x0f\xe7\x1f\x8bF\xa46{\xa4\xb6\x98v\xda\\\x8b\xfc\xcc\xa5\xb1\xefw\x93\xd4i\x1eI$\xb6\xdfP\xf9$\x03\x19\xb5\xe9"0\xdd"\xd9\xbb\xeb\xf5#\xe4\x19\xe2\x80\x8d\xb0\xc3B\xd6\xcd\x0f\x13o\xaag_\xe0\xd9\x9c\x85\x93\x1f\xce\x96T\x9c\xb2Ff;\xb5\xb3\xbe,JA\xd2\x8f\xedp\x00\xeb\xcf\xb5\xe3\x18>\xbc$\xc6\xefA\x18\x13JYB5\xcf\\l\x80~OF\xf80\x9et\x8e\\\xfa\xd1\'\xaf8\xf6,\xc1\xa72\xfal\x96\xfa\xfd$\xccb\x9b\x14\x17>L0\xf3\x8b\x0b\xdb\xf4#\xd3\x1d\x06\xc5eJbv\'\xa7#\xa11\x98\xa6\x8d\x9d\x81\xa8K\x15uB\x07\x0f-\xab\xb17.\x87\xf5+\x12\xbd4\xce\xb3\x1c\xd7m\xac\'yI"\xa7a\xea\xa6mF(\x10j\xc5\t\xb1\xb3\xd8Mg]\xd3\xb6I\x92\xc0\xc0#\x93\x12\xc1\\\x92\xb49\xf0\xa0\x1c\xdf\xf8w\xb1d\xee^9\x15<ej\xbf\xbb\xb2\xd5I\x95=H\x1a\x1e\x89\x98\x83\xa6\x03\xb5\x1b\xae-p\xc0\xc0\xdb7\x01e\xa29\xadk\xea#\xcb6\xa3xNZ$\xa8?\x8b\xa7t\x81o\xa2\xaf\xac\x89\xd0L\xeaO\xa4\x8e\xeb7:\xf4\x1d{\\\xafb\xdbVc\xd8\xbe\x1f\xc1\x98\x8c\xca\xa5\xc0\xb2\xcc\xd7\xc8\xc20\xcd\x82\xc6c\xa6oN\x93Fg\xe1\xc0\x8f\x1axa\x06^4p\x9a\x0e\x1eO\xae\xdbW\x87[\x97{\xfd\xab\x9b\xed\x93\xbdSvV>\xf4\xb2\xdap\xa7I\xe3*\xaa]&\xb0\x04\xd0p\xfb\xfc\xf2\x8c\x9dA\x0e\x88=l\x8c>r\xeb\xc6\x15\xbbvhGVc\xe5\xc0 \x1b\xae\xc6NS?\xb5\xe2\xea<\x9e8^\xb8\xa4\ny\xa9\xaa8da\xf9\xd3&\xca.\x0c\xcfI\xa2\xa4q\xfaN\xecJ\xd6\t\x89\'x\xd8\xea\xfa\xa4\x8fR\x83\xd8H\xc3\xd8\t\xf7?\x12\xd7\x1e\x9a\xae\xd9O\xc0\x0e\x90\xc287Q7iL\xd2\x1c.\xd8U\xe08\xf3>\xddt\x00;\x9b\xd5\x9cQ\x80\xf6\xd7^\x02\x8f\xc5\x0cJw\xcb\xb4\xcc\xf7\x1d\xb3!,\xcfE\xc5+s\x1d\xb6\x1b\xa7\t\x02P\xa5v\xb6\xeb\x90\xb9\xc1\xd8ukp\xa2\xb8\x19&8\xe1B*\xc3n\x02\x86iO\x9b\x0b@\x9au`,\x8d\x05H\x10\xc3\xe7\xeb$\xcd3gbG\xa4q\xfaoG\xf1\xd02\x1be\xf6B\x87v\x18\xcd\x96\x9dj;\xe8\x1e\xe7K\xccf\xd4C`\xd2\xeeB\x99\xe37=\x058\xd6f\xa5\xe6\x04\x06\xd3\x86&\x92Q\n\x9e\xb4QFWm.\x0c vC\\\xe3\xc4YH\x039I\xd3\xe2\x9bq\xa4\x8f\xc1l\xbd\x19\x7f"6\n\xfcl!\x1d4n\xb6\x1b\xf9\xcd\x11Gf\xda@\x19\xda\xd5|\xfc\x1b\x91\xc6x\xe2\xd0C>\xf1B\xa0\x9c4\x85\x94X\xd3\xe6\x18\x12\xdfk\xe4sH3\xb6\x8e\x9a\xa3\xcc\x12\xbba!d\xeaa\xbcWo\xe7-]P\x927\'\x0b\xbdy;\x19\xd9S\xd7i\x88j\xe4\x0f\x1b\xd1T\xe4\xfb\xf3\xad\xbbQ6\x99+\x08\x86`c\r\x87N\x92fI\x167\x8b  \xa1Q\xa9\xc8wK[Nbl\x0c<c\xad\xc4\x0fI\xb3 kV\x99\xceW\x89\xd2\xf9`r\xd1\x08\x13\xcf\r\xe6\xaad!\xc5q\x06\x19\x0b\x13\x18\xa6\xf5\xbcj\xe0$\xe8EX\xc8\x8d\x9a\xdc\x86\x9dK\xba\x86\x0c\xf0\xb2\xdbF\xa5(\\\xbdi\xa0\x95\xd2w*\x85\x91\x8f\xa6U\x85\xe5P\x10\x81\xb2)|~a\xcd\x05\xb1\xe1\xdc\xfee-r\xed1\x89Y\xdc@\xa8c\r\xa3xe\xe0\x1b\x13\xcf\x9cu\xf1U\x1f\xda}Me\xc2h\xe4\xe6\xf3\xce\xa3\x910J\xd2\\Ha\x94\x95\xf2\x84B\xff\xc7\xc7DFnT\xf9\xeb(\x0e\x9f\x01\x0c\xc3\xb8o\x99I\xb9\xed\xfa\xbe\xec\x9cx\\\x137\x89\xc7\xcd\xa8\x02\x8a\x06\x18\x1a\xe4\x0b\xff\x1cZ\t\xc1\x01#\xf3\x9c\r\xe0\xc5lz\xa5\xcc\x0c\xc3\xa6c\xcf\x1aV\x98\x99\xa3 \xad\x07L\x89\xd90\xca\x81\xdb\x00\xd6\xa4i\xed\xa6\xd9\x04\x9d:\xa2\x17\xe2\xf1,s\xc1%\xa6\r\xa4\xc8\xa6o\xcdd\xe8\xb0\xe9\xcaB\x07\xa3\x99\xda\x00\xa1\xa09\xc9h2lV\xc1\xd5\x7fl\x90N\x96\xac\xc8\x1aT]s\\\xd3\x0b\x87,\xe6\x87\xa2\xbf\xf00}\xcb\x80=\x1bM\xec\xbat\xa3IX\xbft\xcc\xc13\x89\x1b+\x02\x85\x9e\xbbX6\x1c\xf8\x8dB\xd88\xccX\xc9\xabc\xd9\x83-\xcf\x0b\xa7\x87a\x92\x9e\x9a>9\x8fa\xe9^K9T\xf7\xbfD\xf31\x10\xdcH\x9b0\x80E\xee|\xe4\xed\xc6!\xc3A\xd0;?,\xb4\xba]^\xc2F%\x0c\x9cfi\xfe\nJ\xb3\xa0\x1f\x15\x83\xab\xca\x8bmW\x9f\xdak\xad\xdc\x87-`\x9fx\x04\xdf\x82\xe9\xa3\xa7Z\xd2\xe7\xca:ey\x19-\xe6\xa5a\xecB!}\x15\x86:\x93\xbc\xd4\x8c\xe3p\xda7=\xd8\x18\xe234\xd4-z\xc2\x03\x1c\x889!\xae\xc3\rFe\xe7po\x04\x91\\\xfeh\xe3F\xf9\x10\xdd\xfb\xce\xdf\xf2\xcdx\xdcw\xdc\xc4w\x93\x848X\t+7*e\xe0;\xfc\xe2\x15\x82>\xbe%\xe0\x06\xc3F\x15\xdb\x0b\xa1\x92\x95\xa5)}\xa7g~\xea\xf86KsAL;\xad\xc7\xceEE\x1f\x16\xa4\n\xaa\xd9\xac\xdd$_\x97\xd743\xbdf\xcf\xb8\x19\xf5L\xf8\xa4/\xfd\xd4\xb7\xbd\xcds:\xdb\x9e\xc2\xb8\xf4\x12\xe7\xb2\xb4\xe2\x1aQ\xf5\x9f\x8b^\xcc\x0c\xbd\xe1\xdc\xc1\x8bE\x1a\x0e\xc6\xf1\x1a\xc0\x08\x16C\x0f,\xc0n{l.\x18\x9fC\x88\xe3#W\x82d\xe8\xd6\xb7v\xf7O;\xf6d_\xea_\x86\xea\x96y|\xbesu&{\xdb\xaa{\xf8z\xe6Y\xe2\xeb\xc5\x858y\x96\xbc\xcf\xe3\xf0Y\xdf\xbd\xed\xed\x06\x9e\xf3\xe6J\xbb\xfc\x81\xfb\xea\x7f\x1e\x8fI\xff\xfe\xd8\x8a\xa6\xd9\xf0\xf5\xe4\x15\xb7`\xcf9\x10%I\x9a\xcd\xedT4\xcaGh#z\xb7wN\xfa\x17j\xefm\xe0\xde\'\xbb\xfb\xb7\xd73{\xab\xe7\xdc>\xdf\x90\x93\x0bh`\x88L\x9c\xdc\x9d \xa5\xe3\xb1L\xfe\x97d\x822\xe1^f\xb2K\xd6F\x99\xb4+s\x97eV\xb3L\x86\x979\xbc\x92\xadQ\xe6\x8fJFCy\x8c[\xe6\x07\xcbLD\x99\xf2f\xf96F\x05a\xb95F\xf7`\xf9"F]`\xc7\xdb,q\xca\xf2|\x8c\x8aR;&.\x12\x90,\x9d\xc22\xf8\xecT\x9e\xe5\x7f\xd9\x992\xcbR\xb2\xec\x1d#\x94\xb0\xa3q\x96teG\xca,9\xc92\x1e,\xb7^K\x05\xb0\xa4sq\xb4\xcd\x92\xa6,s\xc1r\xe4,)\xc4\xf8\x08UR\x87\xd1\x07\xca\xb4"c\xba\xb0\xd4#c\xc3\xb0l\x07\xcb\xab\xb3\x04\nK\xd5\xb3\x04\x12\xa3*\xb0,\r\xe3\x03\xb0Sx\x96\xdfe\x997F\xfe`\xc9\x00\x96f.O\xdak9\xdb2\x93\xc48\x0b,\xa1\xc5\xa8\x13\xb5t\x1fc\x9c\xb0T&c\xd7\xb0\x9c\x02\xcbV\x17I\'Fo\xa8\xa5\xb8\x18\x99\xa2HN2\x9e\x0cK\x183N\x13\xcb\x962\x02\x0f\xcb\x061\xdeA-m\xc1\x12\xe2E\xb2\x98\xf1\x98X\n\x87\x91\x05X\xf6\x92\x11hX\xd2\x97\xf1\x90\xea\x89]\xc65\xca\x13*,U\xcf\xf2M\x8c\xd9PO\xac\xb0\x94}\x9eif\xe4\'\x96)f\xe4%\x96\xd9ed#\x96\xf2dl\x1b\x96cg4\xb0Z\xee\x86\xb1\x02\x8a\x04/\xe3\x1a\xb1D\x11\xa3 \xb0\xb4\'c\xdc\xb0d*\xe3\xf1\xd43\x81\x8csR\xe6&\x19\x0b\xa6H\x122:\n\xcb\x1c1N\x02\xcb\x941N\x06Km2\x12M\x95\xdad$\x9a2/\xc7\x18 ,A\xc8\xa8(,\xcf\xc6\x18\x1c\xb5\x8c\x1d\xe3\x86\x14ig\xc6|b\xb9R\xc6\xcaa\tJF\x85a\xe4\x04\xc6\x9fcyhF\x81b\x19cFVb\xcc\x00FV\xab\xf2\xd9%\xa5\x8ae\xe6\x18\xe7\xa3\xa2\n0\xf6Z\x99Ng\x8c.\x96\xe1c\xdc\x91\x8a<\xc0\xf8l\x15\x89\x81\xf1\xea\n:\x01c\xb8\xb1\xdc9\xa3m\xb1\x9c.c\x0f\xb1\xd4(#\xe1T\xc9|\xc6\'c\x84\x0b\xc6\x01\xacx\x12\x8c\xbaW\xa6h\x19\x19\xa8L;3\x82\x13\xa350\xa6\x1dc`0R \xcb\xd53\x9a\x18KV3Z\x14K\xbd2RO\x8d\xae\xc1\x18\x84\x8cK\xc1\xe8}%\xff\x80Q\xe0\xca\x9c?\xa3\x9b\xb1t6#NUy[\xc6\x08\xaa\xd2\x9c\x8c0S\xd2\x17\x18s\xae\xcc\xf93v\x19c\x0c0n\x1a\xcb\xf43NY\xc5\x0cadE\x96\x1dg<,\x96yg\x1c\xaf\x92\x16\xc0\x08h\x15\xc1\x82q\xfc\xca\x8c,\xe3\xf60\x1a\x08c"\xd6\x13\xba\x8c\x1a\x94\xb3Y\x18\xc1\x921M\x18\xe9\xb1\x96\xfde<\xa2"c\xcd\xb8P\x8cK\xc2\xe8\x8c,\xfd\xce\x88^\x8cc\xc12\xfb\x8cC\xc6\xc8,\x8cW\xc9\xc8\x16\x8c\xd6\xc7\xb2\xea\x8c\xaf\xc5\xc8A\x8c\xaf\xca\x18\x06\x8c\xcb\xc6\xe8*\x8c1\xc9R\xf1\x8c\xe4\xc5\xf86\x8c\xfaY#!\x14t\xb7\x8a*R\xd1\x13\x1bD\x94\x8a\x04I9\n\x15\x1d\xae\xa2\xa9T\x14\xc99\x02A\xc5M+\xe8>\x15\xf5\xb4"(T\\\xb8\x8a\xd0Pq\xe7*\xaaUE\x03\xae\x88U\x15\xd9w\x8e\x12T\xd1R+\x92ME\xf0,\x18!\x15\xf9\xb0\xa23TL\xb99\xb2WED.(\x11\x15\xdb\xaeb\xc6T$\xcc9\x9aOE1-X.\x15\xa1\xb2\xa2\x7fVl\x83\x8a\xb8V1\xd0*\x96t\xc52\xab\x18\xd0\x15\xbf\xaa\xe2\xfcVT\x98\x8au9G4\xaaH\xae\x053\xacb+W\x94\x97\x8a\x1fWq\xb8+\xbeZ\xc5\xa1\xae\xd8.\x15\xb1\xb2N\xcc\xaa\xc8\xc1%\xa1\xaa"\xf5\xd6\xa965V\'\xe3\x06U4\xd4\x92VR1\x16+FKE\x9a\xac\xe8#\x153\xb1b\x89V$1FTF6Gl\xd3\xad\xa5=\xc1\xad\xce\xd37\xb69t\xdc\xe6\x01\x8e\xdb\xe0\x14\x98\x03\xa7\x99\r\t\xe2\x81\xb3X\xd2$\xf5\'\x8e\xd5<\x00\xb3\xe7\xb3\x18\x8e=\n1\xd9Z\x1e\xf3\xf9\x84\xa4\xf5#\xba\xf2$\xc7\x9df5\x9a\xc90\tq\x8c\xf4\xa2?LL+i\x7f\xdbh\xd5^\xeb\xb1\xc9x\xb3\x85;\xbb\xd6F\xcb\x1d\xb4>\x96\xef\x16\xed\x9e\xed\\\xf5\xcb7\x8a>\xb5\xbe\xd6\xae\x1f?\xb8\x03\xc7s><m\x06d\xda\xda\x85}\xff\xc7O\xdd!I\xaf]\x1f\xbe\xd1\xdf1\xf9\xfb\xdfg\xf2\xfe\x96\xf7\x99\x8a\xd7\xfe\x91\x05@\xe2\xdd\xe2\x8d\x7f;\x0c\x06\xeep\xbd\xf5\xf5\x83\xeb|Xo}x7\xd7\xfc\x81k}\xa0\xc7CX{\xe5o\x95`M7\xe9\xa5\xc4\xbf\x8e\xcddD\xb0\xfd\x16]\xe6\x16\xdcq\x8a\x1fM\xb9$y\xfe\xff\x88\xcc\xb0\xc5\x0f\xdc\x07\x12\x98\x96G\xf6\xf0\x88n\x97\x1e\xf2A9\xd5\x85\x0f\xec\xc4v\x9f\x10\xc72\xedq\x8f\x8e\xd9\x80\x08\x91\xc7\xde\x16\xeeog\xf6\x98\xa4X\'\x9fugJ\xac\x0f\xdc7\xae\x95O\xfbs\x12\x06\xeb\xad\xc7v{\xe9\xdbw\x0b/\xbbb\x1e\xff\xb1^\xda\xde\xea\xbd\x99W\xb3\xdd\xdb\x8b\xa9\xac\xecN\xc3\xfb\x11\x84\x8d\xc3Ir\xaeL\xcew_\xf6\x8e&V\xe7~\x1aXz\x9b\xe3\x97\xf6P<\xbf#\x90\x0b\xe1\xf5Y5z\xce\xf5\tq]%\xd6\xac8\x91.\r\x9e\xd8\xe3\x8e\xaf\x8d\xdb\xe5i&=\xcc\\\x9b\x88\x16I\xcdv\xc1\x15X\x180\x16\x82)\xd3\xef`\xdc\xdc\x8a\x03\xff\xe2\xb1\xf7j\x14\xcd.\x97\xcar\x81=>\xb6\x9b$\xab\xbc\xce\x13\xa7RA.<\xfb\xf87\x1f\xfc\xc0\xb4V\x1d\xeb,\x9c\x04\xfd<\xd7\xf9y\xae\xf3\xf3\\\xe7\xe7\xb9\xce\xcfs\x9d\x9f\xe7:?\xcfu~\x9e\xeb\xfc<\xd7\xf9y\xae\xf3\xf3\\\xe7\xe7\xb9\xce\xff\x0f\xe7:OOKvhKw\xa4\xe5N\xd0\xb4\xed0\x0b\xe6^\x8aX\xbb"\xf1\xc4\xb5\xc9q8t\x83\xdf\x93\xfc"\x7fw`\xea&\xf4\x9b\xa8Ff\x92\xc0\x1e2/\x06\x85\x02T\xe7\xf3;\xc8Qp\x83\xac\xb8\xf5\xb7\xfe\x8c\xe8\x7fI\xbb\xe5\xdb\x0by_#/\xefe\x10\xe7\xd7\x83\x10I5Y\xf4\x9f\xed{\xe1\x18\x81\x12\xf9\x97\xef\x8f\xbf\xff\x16P\xb9\x1d\xce7\xddO\\u\xea5\x0b\xb34\xb3H\xe3\'-\x97\

In [59]:
import requests
import pandas as pd
import io

url_data = 'https://drive.google.com/uc?id=1-bsOZer49Cz0g1xNK1ygk657k94Jilu3'  # URL Public
url_client = 'https://drive.google.com/uc?id=1-ZX9AKIhO6rFqbcd3sOqdp3rPtZkD4QA'

try:
    response = requests.get(url_data, stream=True) # stream=True est important pour les gros fichiers
    response.raise_for_status() #Vérifie le code de statut HTTP

    df = pd.read_csv(io.BytesIO(response.content)) # Lecture depuis la mémoire
    print(df.head())

except requests.exceptions.RequestException as e:
    print(f"Erreur de requête : {e}")
except Exception as e:
    print(f"Autre erreur : {e}")

Empty DataFrame
Columns: [<!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="gBa_uUOLxcdGi72eBwRTMw">.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial, sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption, .uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}sentinel{}</style><link rel="icon" href="//ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for viruses.</p><p class="uc-warning-subcaption"><span class="uc-name-size"><a href="/open?id=1-bsOZer49Cz0g1xNK1ygk657k94Jilu3">application_train_features.csv</a> (224M)</span> is too large for Google to scan for viruses. Would you still like to download this file?</p><form id="download-form" action="https://drive.usercontent.google.com/download" method="get"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/><input type="hidden" name="id" value="1-bsOZer49Cz0g1xNK1ygk657k94Jilu3"><input type="hidden" name="confirm" value="t"><input type="hidden" name="uuid" value="50763434-6762-4ab3-8045-99828b6656f0"></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>]
Index: []